parameters:
  - name: 'stage'
    type: string
  - name: 'project'
    type: string
  - name: 'apiname'
    type: string
  - name: 'datasource'
    type: string
  - name: 'users'
    type: string
  - name: 'durations'
    type: string
    default: ''
  - name: poolName
    type: string
    default: 'Azure Pipelines'
  - name: vmImage
    type: string
    default: 'ubuntu-latest'

variables:
  - group: Shared
  - group: Automation_Variables
  - group: CCE_Automation_Variables

stages:
  - stage: ${{parameters.stage}}
    pool:
      name: ${{parameters.poolName}}
      vmImage: ${{parameters.vmImage}}
    jobs:
      - job: perf_API_Tests
        timeoutInMinutes: 360
        displayName: Performance API Tests
        steps:
            - parameters:
                script: bash scripts/perfAPICmdString.sh $(System.StageDisplayName) ${{parameters.project}} ${{parameters.apiname}} ${{parameters.datasource}} ${{parameters.users}} ${{parameters.durations}}
                displayName: Executing Performance test for CMPortal APIs in Azure Pipelines

