parameters:
  - name: 'stage'
    type: string
  - name: 'project'
    type: string
  - name: 'apiname'
    type: string
  - name: 'datasource'
    type: string
  - name: 'users'
    type: string
  - name: 'durations'
    type: string
    default: ''
  - name: poolName
    type: string
    default: 'Azure Pipelines'
  - name: vmImage
    type: string
    default: 'ubuntu-latest'

variables:
  - group: Shared
  - group: Automation_Variables
  - group: CCE_Automation_Variables

stages:
  - stage: ${{parameters.stage}}
    pool:
      name: ${{parameters.poolName}}
      vmImage: ${{parameters.vmImage}}
    jobs:
      - job: perf_API_Tests
        timeoutInMinutes: 360
        displayName: Performance API Tests
        steps:
            - script: |
                sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
                echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
                sudo apt-get update
                sudo apt-get install k6
              displayName: Install k6 tool

            - script: |
                k6 version
              displayName: Check if K6 is installed

            parameters:
              script: bash scripts/perfAPICmdString.sh $(System.StageDisplayName) ${{parameters.project}} ${{parameters.apiname}} ${{parameters.datasource}} ${{parameters.users}} ${{parameters.durations}}
              displayName: Executing Performance test for CMPortal APIs in Azure Pipelines
