trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: DEPLOYMENT_ENV
  displayName: DEPLOYMENT_ENV
  type: string

- name: DEPLOYMENT_PROJECT
  displayName: DEPLOYMENT_PROJECT
  type: string

- name: DEPLOYMENT_API_NAME
  displayName: DEPLOYMENT_API_NAME
  type: string

- name: DEPLOYMENT_DATA_SOURCE
  displayName: DEPLOYMENT_DATA_SOURCE
  type: string

- name: DEPLOYMENT_USERS
  displayName: DEPLOYMENT_USERS
  type: string

- name: DEPLOYMENT_TEST_DURATION
  displayName: DEPLOYMENT_TEST_DURATION
  type: string


  
stages:
- stage: PERFORMANCE_TESTING
  variables:
   - name: src_env
     value: ${{parameters.DEPLOYMENT_ENV}}
   - name: src_project
     value: ${{parameters.DEPLOYMENT_PROJECT}}
   - name: src_api_name
     value: ${{parameters.DEPLOYMENT_API_NAME}} 
   - name: src_data_source
     value: ${{parameters.DEPLOYMENT_DATA_SOURCE}}       
   - name: src_users
     value: ${{parameters.DEPLOYMENT_USERS}}       
   - name: src_test_duration
     value: ${{parameters.DEPLOYMENT_TEST_DURATION}}       

  jobs:
  - job: ExecutionEnvironmentSetup
  
    steps:
     - script: |
          echo $(Build.SourcesDirectory)
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
       displayName: 'Install K6'
  
     - script: |
          pwd
          echo $(src_env)
          echo $(src_project)
          echo $(src_api_name)
          echo $(src_data_source)
          echo $(src_users)
          echo $(src_test_duration)
          echo '$(Build.SourcesDirectory)'
          bash $(Build.SourcesDirectory)/scripts/perfAPICmdString.sh $(src_env) $(src_project) $(src_api_name) $(src_data_source) $(src_users) $(src_test_duration)